// lib/tokens.js
// Game-token regen system — was referenced by api/auth.js (and read back
// out by api/init.js's periodic sync) but the file itself was missing from
// the repo, so every require('../lib/tokens') crashed the serverless
// function before it could even verify the Telegram initData. That's what
// was producing the "Connection failed" screen in the mini app: the
// function never got a chance to return a real response.
//
// Behaviour (matches what the frontend already expects — see index.html's
// "X/10" token display and the (+1 in Xh Ym) countdown that reads
// nextTokenAt):
//   - Users start with 3 tokens (set in api/auth.js's newUser object).
//   - Tokens regen passively over time, up to MAX_TOKENS.
//   - One new token every TOKEN_REGEN_INTERVAL_MS of elapsed time since
//     lastTokenRegenAt, computed fresh on every call (no cron needed).
//
// NOTE: 30 minutes/token is a placeholder default — tune it in one place
// here (or move it into the `settings` Mongo collection like
// lib/settings.js does for withdrawal fees, if you want it admin-editable
// without a redeploy).

const MAX_TOKENS = 10;
const TOKEN_REGEN_INTERVAL_MS = 30 * 60 * 1000; // 30 minutes per token

// Pure function: given a user's current tokens + last regen timestamp,
// figure out how many tokens should have regenerated by now.
function computeRegen(gameTokens, lastTokenRegenAt) {
  const current = typeof gameTokens === 'number' ? gameTokens : 3;
  const lastAt = lastTokenRegenAt ? new Date(lastTokenRegenAt) : new Date();

  if (current >= MAX_TOKENS) {
    return { gameTokens: MAX_TOKENS, lastTokenRegenAt: lastAt, nextTokenAt: null };
  }

  const elapsedMs = Date.now() - lastAt.getTime();
  const tokensGained = Math.floor(elapsedMs / TOKEN_REGEN_INTERVAL_MS);

  if (tokensGained <= 0) {
    const nextTokenAt = new Date(lastAt.getTime() + TOKEN_REGEN_INTERVAL_MS);
    return { gameTokens: current, lastTokenRegenAt: lastAt, nextTokenAt };
  }

  const newTokens = Math.min(MAX_TOKENS, current + tokensGained);
  // Carry forward only the "used up" regen time, so partial progress
  // toward the next token isn't lost/reset.
  const consumedMs = tokensGained * TOKEN_REGEN_INTERVAL_MS;
  const newLastAt = new Date(lastAt.getTime() + consumedMs);
  const nextTokenAt =
    newTokens >= MAX_TOKENS ? null : new Date(newLastAt.getTime() + TOKEN_REGEN_INTERVAL_MS);

  return { gameTokens: newTokens, lastTokenRegenAt: newLastAt, nextTokenAt };
}

// Atomic (compare-and-swap) DB update — reads the user's current stored
// values, computes regen, and writes it back only if nothing else changed
// those fields in the meantime. This is what the comment in api/auth.js
// refers to when it says the old "read → compute → blind-$set" pattern
// could double-apply a tick jump when api/auth.js and api/init.js's
// periodic sync raced each other.
async function applyRegen(usersCol, user) {
  const before = {
    gameTokens: user.gameTokens ?? 3,
    lastTokenRegenAt: user.lastTokenRegenAt || new Date(),
  };

  const regen = computeRegen(before.gameTokens, before.lastTokenRegenAt);

  // Nothing changed — skip the write entirely.
  if (regen.gameTokens === before.gameTokens) {
    return { gameTokens: before.gameTokens, lastTokenRegenAt: before.lastTokenRegenAt };
  }

  const result = await usersCol.findOneAndUpdate(
    {
      _id: user._id,
      gameTokens: before.gameTokens,
      lastTokenRegenAt: before.lastTokenRegenAt,
    },
    {
      $set: {
        gameTokens: regen.gameTokens,
        lastTokenRegenAt: regen.lastTokenRegenAt,
      },
    },
    { returnDocument: 'after' }
  );

  // If the CAS missed (another request already regenerated tokens in
  // parallel), just trust whatever's in `result`/re-read value rather than
  // stomping on it.
  if (result && result.gameTokens !== undefined) {
    return { gameTokens: result.gameTokens, lastTokenRegenAt: result.lastTokenRegenAt };
  }

  return { gameTokens: regen.gameTokens, lastTokenRegenAt: regen.lastTokenRegenAt };
}

module.exports = { computeRegen, applyRegen, MAX_TOKENS, TOKEN_REGEN_INTERVAL_MS };
